ENABLE:
  - ACTION
  - CPP
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - CPP_CPPLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - JSON_V8R
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_LYCHEE
PRINT_ALPACA: false
SARIF_REPORTER: true
SHOW_SKIPPED_LINTERS: false
JSON_JSONLINT_ARGUMENTS: --mode cjson
EXCLUDED_DIRECTORIES: 
  - tiva
